import test from 'node:test';
import assert from 'node:assert/strict';
import { createGateSession,linkPolicy } from '../../src/shared/parent-gate.js';
import { createNativeRuntime,isNative,isNativeBuild,nativeLocalHref,selectLocalChineseVoice,gameIsRunning } from '../../src/shared/native.js';
import { TiltController } from '../../src/games/car/tilt.js';

const nativeHost=(platform='android')=>({Capacitor:{isNativePlatform:()=>true,getPlatform:()=>platform},document:{body:{dataset:{}},querySelectorAll:()=>[],addEventListener(){}},location:{assign(){}},speechSynthesis:{cancel(){}}});
const voice=(lang,localService)=>({lang,localService,name:lang,voiceURI:lang});
test('adult gate uses random two-digit operands and permits exactly one approved action',()=>{const g=createGateSession({random:()=>.4,now:()=>100});const q=g.challenge();assert.ok(q.left>=50&&q.left<=89&&q.right>=50&&q.right<=89);assert.equal(g.check(String(q.left+q.right)).approved,true);assert.equal(g.check(String(q.left+q.right)).approved,false);});
test('wrong, expired, cancelled and locked gates never authorize an action',()=>{let now=0;const g=createGateSession({random:()=>0,now:()=>now});assert.equal(g.check('').approved,false);assert.equal(g.check('0').approved,false);assert.equal(g.check('999').reason,'locked');assert.equal(g.check('100').approved,false);const expired=createGateSession({random:()=>0,now:()=>now});now=90001;assert.equal(expired.check('100').reason,'expired');const cancelled=createGateSession({random:()=>0});cancelled.cancel();assert.equal(cancelled.check('100').approved,false);});
test('full-width numeric entry is accepted but expressions and non-finite input are not',()=>{assert.equal(createGateSession({random:()=>0}).check('１００').approved,true);for(const s of ['50+50','Infinity','NaN','100abc','<script>100</script>'])assert.equal(createGateSession({random:()=>0}).check(s).approved,false);});
test('native blocks external links and local downloads; web retains adult-approved destinations',()=>{const base='capacitor://localhost/flight/index.html';assert.equal(linkPolicy('../car/index.html',base,{native:true}).kind,'internal');assert.equal(linkPolicy('https://github.com/mars-tw/taiwan-island-drive',base,{native:true}).nativeBlocked,true);assert.equal(linkPolicy('../downloads/source.zip',base,{native:true}).nativeBlocked,true);assert.equal(linkPolicy('capacitor://evil/index.html',base,{native:true}).kind,'external');assert.equal(linkPolicy('javascript:alert(1)',base).kind,'blocked');assert.equal(linkPolicy('./source.zip','https://example.com/',{native:false}).nativeBlocked,false);});
test('native internal directory destinations become explicit offline entry files',()=>{assert.equal(nativeLocalHref('./car/','capacitor://localhost/index.html'),'capacitor://localhost/car/index.html');assert.equal(nativeLocalHref('../','https://localhost/flight/index.html'),'https://localhost/index.html');assert.equal(nativeLocalHref('./flight/index.html','https://localhost/'),'https://localhost/flight/index.html');assert.equal(nativeLocalHref('https://example.com/','https://localhost/'),'https://example.com/');});
test('native platform and native build flags are distinct from an ordinary web page',()=>{assert.equal(isNative(nativeHost()),true);assert.equal(isNative({}),false);assert.equal(isNativeBuild({},'native'),true);assert.equal(isNativeBuild({},'production'),false);});
test('offline Chinese voice selection prefers Taiwan and rejects network-required voices',()=>{assert.equal(selectLocalChineseVoice([voice('zh-TW',false),voice('zh-CN',true),voice('zh-TW',true)]).index,2);assert.equal(selectLocalChineseVoice([voice('zh-TW',false),voice('en-US',true)]),null);assert.equal(selectLocalChineseVoice([{...voice('zh-TW',true),networkConnectionRequired:true}]),null);});
test('native speech uses a local voice with flush and ambient options',async()=>{let spoken;const rt=createNativeRuntime({host:nativeHost('ios'),loadPlugin:async()=>({getSupportedVoices:async()=>({voices:[voice('zh-TW',true)]}),isLanguageSupported:async()=>({supported:true}),speak:async options=>{spoken=options;}})});const result=await rt.speak('慢慢起飛');assert.equal(result.spoken,true);assert.equal(spoken.voice,0);assert.equal(spoken.lang,'zh-TW');assert.equal(spoken.queueStrategy,0);assert.equal(spoken.category,'ambient');assert.equal(rt.getStatus().hardwareVerified,false);});
test('missing local speech data falls back to text without downloads or install intents',async()=>{let speakCalls=0,installCalls=0;const rt=createNativeRuntime({host:nativeHost(),loadPlugin:async()=>({getSupportedVoices:async()=>({voices:[voice('zh-TW',false)]}),speak:async()=>speakCalls++,openInstall:async()=>installCalls++})});assert.equal((await rt.speak('提示')).spoken,false);assert.equal(speakCalls,0);assert.equal(installCalls,0);assert.equal(rt.getStatus().speech,'text-only');const missing=createNativeRuntime({host:nativeHost(),loadPlugin:async()=>({getSupportedVoices:async()=>({voices:[voice('zh-TW',true)]}),isLanguageSupported:async()=>({supported:false}),speak:async()=>speakCalls++})});assert.equal((await missing.speak('提示')).spoken,false);assert.equal(speakCalls,0);});
test('stopped pending native speech cannot later start after plugin loading completes',async()=>{let resolvePlugin,spoken=0;const rt=createNativeRuntime({host:nativeHost(),loadPlugin:()=>new Promise(resolve=>resolvePlugin=resolve)});const speaking=rt.speak('舊提示');await Promise.resolve();const stopping=rt.stopSpeech();resolvePlugin({stop:async()=>{},getSupportedVoices:async()=>({voices:[voice('zh-TW',true)]}),speak:async()=>spoken++});await stopping;assert.equal((await speaking).spoken,false);assert.equal(spoken,0);});
test('app listeners pause active games in background and never auto-resume on foreground',async()=>{const callbacks={},state={mode:'playing'};let pauses=0,resumes=0;const host=nativeHost();host.document.body.dataset.game='flight';const rt=createNativeRuntime({host,resolveGames:()=>[{game:{getState:()=>state,pause(){state.mode='paused';pauses++;},resume(){state.mode='playing';resumes++;}}}],loadPlugin:async()=>({addListener:async(name,fn)=>{callbacks[name]=fn;return {remove:async()=>{}};}})});await rt.init();callbacks.appStateChange({isActive:false});assert.equal(state.mode,'paused');callbacks.resume();assert.equal(resumes,0);assert.equal(pauses,1);assert.equal(rt.getStatus().lifecycle,'foreground-paused');});
test('Android back closes a gate first, then pauses gameplay, then returns to the lobby',async()=>{let open=true,paused=false,home=0;const host=nativeHost();host.document.body.dataset.game='flight';const rt=createNativeRuntime({host,navigateHome:()=>home++,resolveGames:()=>[{game:{getState:()=>({mode:paused?'paused':'playing'}),pause:()=>paused=true}}]});rt.registerOverlay({isOpen:()=>open,close:()=>open=false});assert.equal(await rt.handleBack(),'dialog');assert.equal(paused,false);assert.equal(await rt.handleBack(),'paused');assert.equal(home,0);assert.equal(await rt.handleBack(),'home');assert.equal(home,1);});
test('only an idle lobby may minimize; back never exits a game immediately',async()=>{let minimized=0;const rt=createNativeRuntime({host:nativeHost(),resolveGames:()=>[],loadPlugin:async()=>({minimizeApp:async()=>minimized++})});assert.equal(await rt.handleBack(),'minimized');assert.equal(minimized,1);for(const s of [{phase:'running'},{phase:'countdown'},{mode:'playing'},{paused:false,completed:false}])assert.equal(gameIsRunning(s),true);assert.equal(gameIsRunning({mode:'paused'}),false);});
test('background closure cannot leave a resumed game running and engine audio is suspended',()=>{let paused=false,suspended=0,muted=0;const host=nativeHost();const game={getState:()=>({paused,completed:false}),pause:()=>paused=true};const audio={ctx:{currentTime:1,suspend:async()=>suspended++},gain:{gain:{setValueAtTime:()=>muted++}}};const rt=createNativeRuntime({host,resolveGames:()=>[{game,audio}]});rt.registerOverlay({isOpen:()=>true,close:()=>paused=false});rt.background();assert.equal(paused,true);assert.equal(suspended,1);assert.equal(muted,1);});
test('a delayed background close is suppressed once without poisoning future dialog closes',async()=>{let capture,stopped=0;const dialog={returnValue:'',close(){}};const host=nativeHost();host.document.querySelectorAll=()=>[dialog];host.document.addEventListener=(name,fn)=>{if(name==='close')capture=fn;};const rt=createNativeRuntime({host,loadPlugin:async()=>({addListener:async()=>({remove:async()=>{}})})});await rt.init();rt.background();rt.foreground();const event={target:dialog,stopImmediatePropagation:()=>stopped++};capture(event);assert.equal(stopped,1);capture(event);assert.equal(stopped,1);assert.equal(dialog.returnValue,'');});
test('native motion permission is requested before loading and denial never attaches a sensor',async()=>{let permission=0,loaded=0;const host=nativeHost();host.DeviceOrientationEvent={requestPermission:()=>{permission++;return Promise.resolve('denied');}};const rt=createNativeRuntime({host,loadPlugin:async()=>{loaded++;return {};}});const result=await rt.requestMotion();assert.equal(permission,1);assert.equal(result.granted,false);assert.equal(loaded,0);await assert.rejects(()=>rt.subscribeMotion(()=>{}),/permission/);});
test('native motion subscriptions forward samples only while active and remove their listener',async()=>{let callback,removed=0;const samples=[];const host=nativeHost();host.DeviceOrientationEvent={requestPermission:()=>Promise.resolve('granted')};const rt=createNativeRuntime({host,loadPlugin:async()=>({addListener:async(name,fn)=>{assert.equal(name,'orientation');callback=fn;return {remove:async()=>removed++};}})});assert.equal((await rt.requestMotion()).granted,true);const stop=await rt.subscribeMotion(v=>samples.push(v));callback({beta:20,gamma:5});rt.background();callback({beta:20,gamma:8});assert.equal(samples.length,1);await stop();assert.equal(removed,1);});
test('native preferences restore and write only the supplied local key',async()=>{let listener,written;const rt=createNativeRuntime({host:nativeHost(),loadPlugin:async()=>({get:async({key})=>{assert.equal(key,'family');return {value:'{"muted":true}'};},set:async value=>written=value})});let restored;await rt.syncPreferences({key:'family',read:()=>({}),update:value=>restored=value,subscribe:fn=>{listener=fn;return ()=>{};}});assert.deepEqual(restored,{muted:true});listener({muted:false});await Promise.resolve();assert.equal(written.key,'family');assert.equal(written.value,'{"muted":false}');});

function sensorHost(){const listeners=new Map();let time=0;return {Capacitor:{isNativePlatform:()=>true,getPlatform:()=> 'ios'},isSecureContext:false,DeviceOrientationEvent:{},performance:{now:()=>time},screen:{orientation:{angle:0,addEventListener(){},removeEventListener(){}}},addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:n=>listeners.delete(n),requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setTime:v=>time=v};}
test('native tilt retains fresh-sample readiness instead of declaring ready on permission approval',async()=>{const host=sensorHost();let callback,removed=0;const tilt=new TiltController({host,nativeMotionBridge:{request:async()=>({granted:true}),subscribe:async fn=>{callback=fn;return async()=>removed++;}}});assert.equal(await tilt.enable(),true);assert.equal(tilt.getState().ready,false);callback({beta:0,gamma:0});assert.equal(tilt.getState().ready,true);tilt.setActive(true);host.setTime(100);callback({beta:0,gamma:20});tilt.tick(100);host.setTime(200);tilt.tick(200);assert.ok(tilt.steer>0);host.setTime(1000);tilt.tick(1000);assert.equal(tilt.steer,0);tilt.disable();assert.equal(removed,1);assert.equal(tilt.getState().ready,false);});
test('native tilt denial and cancellation remove pending subscriptions without claiming hardware readiness',async()=>{const host=sensorHost();const denied=new TiltController({host,nativeMotionBridge:{request:async()=>({granted:false,status:'denied'})}});assert.equal(await denied.enable(),false);assert.equal(denied.getState().ready,false);let resolveSubscription,removed=0;const tilt=new TiltController({host,nativeMotionBridge:{request:async()=>({granted:true}),subscribe:()=>new Promise(resolve=>resolveSubscription=resolve)}});const enabling=tilt.enable();await Promise.resolve();tilt.disable();resolveSubscription(async()=>removed++);assert.equal(await enabling,false);assert.equal(removed,1);});
