import test from 'node:test';
import assert from 'node:assert/strict';
import { FlightGame } from '../../src/games/flight/game.js';
import { AIRCRAFT,MAPS,MAP_EXTENT } from '../../src/games/flight/config.js';
import { stepPhysics,wrap } from '../../src/games/flight/physics.js';
import { newMission,updateMission,predictedMailImpact } from '../../src/games/flight/mission.js';
import { createFlightInitialState,createChildPilot,updateChildPilot } from '../../src/games/flight/child-pilot.js';
import { childAction } from '../../src/games/flight/child-instructions.js';

const STEP=1/120;
function makeGame(mode,map='coast',plane='trainer'){
 const game=Object.create(FlightGame.prototype);game.state=createFlightInitialState(mode);Object.assign(game,{lesson:mode,map,plane,preschool:true,assist:true,mode:'playing',keys:new Set(),controls:{pitch:0,roll:0,rudder:0,throttle:game.state.throttle,flaps:game.state.flaps,brake:0},guidance:{rotate:false,navigate:false,land:false,pilot:createChildPilot(game.state)},mission:newMission(mode,map),audio:{start(){},update(){}},world:{loaded:true,view:'chase',terrainHeight:()=>0,onRunway:p=>Math.abs(p.x)<24&&p.z>=0&&p.z<=1800}});return game;
}
function step(game){const c=game.input(STEP);game.effectiveControls=c;stepPhysics(game.state,c,AIRCRAFT[game.plane],STEP,{assist:game.useStabilization(),onRunway:game.world.onRunway(game.state.position)});updateMission(game.mission,game.state,STEP,{progressPaused:game.guidance.pilot.returning});return c;}
function fly(game,seconds=400,stop=()=>game.mission.complete||game.mission.retry){for(let i=0;i<seconds/STEP&&!stop();i++)step(game);return game;}

test('one child tap performs real takeoff phases on both planes without another tap',()=>{
 for(const plane of Object.keys(AIRCRAFT)){const g=makeGame('takeoff','coast',plane);const initial=structuredClone(g.state);g.childControl();assert.deepEqual(g.state,initial);const stages=new Set();for(let i=0;i<100/STEP&&!g.mission.complete&&!g.mission.retry;i++){const before={...g.state.position};step(g);stages.add(g.guidance.pilot.stage);assert.ok(Math.hypot(g.state.position.x-before.x,g.state.position.y-before.y,g.state.position.z-before.z)<1);}
  assert.equal(g.mission.complete,true);assert.equal(g.state.takeoffOnRunway,true);assert.equal(g.state.rotationCommanded,true);assert.ok(g.state.time<80);assert.ok(stages.has('accelerating')&&stages.has('rotating')&&stages.has('climbing'));}
});
test('repeated ground taps are queued and never steer the child off the runway',()=>{const g=makeGame('takeoff');g.childControl();for(let i=0;i<40;i++)g.childTurn(1);assert.equal(g.guidance.pilot.targetHeading,0);fly(g,90);assert.equal(g.mission.complete,true);assert.equal(g.state.firstLiftoff.onRunway,true);assert.ok(Math.abs(g.state.firstLiftoff.position.x)<1);});
test('tap right turns right and releases back to a physically completable navigation route',()=>{const g=makeGame('navigation');g.childControl();const initial=structuredClone(g.state);g.childTurn(1);assert.deepEqual(g.state,initial);fly(g,3,()=>false);assert.ok(g.state.heading>0&&g.state.position.x<0);assert.ok(Math.abs(g.state.bank)<.4);fly(g,100);assert.equal(g.mission.complete,true);assert.equal(g.guidance.pilot.turnRemaining,0);});
test('repeated same-direction taps cannot accumulate an unbounded route turn',()=>{const g=makeGame('treasure');g.childControl();for(let i=0;i<100;i++)g.childTurn(-1);assert.ok(Math.abs(wrap(g.guidance.pilot.targetHeading-g.state.heading))<.71);fly(g,180);assert.equal(g.mission.complete,true);assert.ok(g.state.time<180);});
test('all three new games physically complete on four scenes with both planes',()=>{
 for(const plane of Object.keys(AIRCRAFT))for(const map of Object.keys(MAPS))for(const mode of ['treasure','mail','tour']){const g=makeGame(mode,map,plane);g.childControl();fly(g,500);assert.equal(g.mission.retry,false,mode+' '+map+' '+plane);assert.equal(g.mission.complete,true,mode+' '+map+' '+plane);assert.equal(g.mission.passed,g.mission.total);assert.equal(g.mission.progress,1);assert.ok(g.state.time<300);if(mode==='mail')assert.equal(g.mission.events.filter(e=>e.type==='mail').length,2);}
});
test('first treasure feedback occurs early and requires actual proximity',()=>{const g=makeGame('treasure');g.childControl();fly(g,25,()=>g.mission.passed>0);assert.equal(g.mission.passed,1);assert.ok(g.state.time<15);assert.equal(g.mission.targets[0].visited,true);assert.equal(g.mission.events[0].type,'star');});
test('mail progress waits for the real falling parcel instead of crediting the flyover',()=>{const g=makeGame('mail');const target=g.mission.targets[0];const impact=predictedMailImpact(g.state);g.state.position.x=target.x;g.state.position.z=target.z-g.state.velocity.z*impact.time;g.mission.autoDrop=true;updateMission(g.mission,g.state,STEP);assert.ok(g.mission.activeParcel);assert.equal(g.mission.passed,0);const height=g.mission.activeParcel.position.y;for(let i=0;i<120;i++)updateMission(g.mission,g.state,STEP);assert.ok(g.mission.activeParcel.position.y<height);assert.equal(g.mission.passed,0);for(let i=0;i<120*8&&g.mission.activeParcel;i++)updateMission(g.mission,g.state,STEP);assert.equal(g.mission.passed,1);assert.equal(g.mission.events.at(-1).type,'mail');});
test('tour needs stable time in the sightseeing area rather than one-frame contact',()=>{const g=makeGame('tour');const t=g.mission.targets[0];Object.assign(g.state.position,{x:t.x,y:t.y,z:t.z});updateMission(g.mission,g.state,STEP);assert.equal(g.mission.passed,0);for(let i=0;i<120*3;i++)updateMission(g.mission,g.state,STEP);assert.equal(g.mission.passed,1);});
test('return-home and cancellation only change guidance, never the flight position or velocity',()=>{const g=makeGame('treasure');g.childControl();fly(g,10,()=>false);const physical=structuredClone(g.state),earned=g.mission.passed;g.returnHome();assert.deepEqual(g.state,physical);assert.equal(childAction(g.getState())[0],'取消返航');const target=g.guidance.pilot.returnRoute[0];g.returnHome();assert.deepEqual(g.guidance.pilot.returnRoute[0],target);g.childControl();assert.deepEqual(g.state,physical);assert.equal(g.guidance.pilot.returning,false);assert.equal(g.mission.passed,earned);});
test('return-home physically lands both planes in child and parent settings',()=>{for(const plane of Object.keys(AIRCRAFT))for(const child of [true,false]){const g=makeGame('navigation','coast',plane);g.preschool=child;g.assist=child;g.returnHome();fly(g,650,()=>g.guidance.pilot.stage==='parked'||g.mission.retry);assert.equal(g.guidance.pilot.stage,'parked',plane+' '+child);assert.equal(g.state.grounded,true);assert.equal(g.state.touchdown.onRunway,true);assert.ok(g.state.airspeed<1.5);assert.equal(g.guidance.pilot.returnIndex,4);}});
test('mission view exposes stable target and progress fields without mutating mission data',()=>{const g=makeGame('treasure');g.childControl();const original=structuredClone(g.mission);const s=g.getState();assert.equal(s.mission.total,6);assert.equal(s.mission.targets.length,6);assert.equal(typeof s.mission.targetLabel,'string');assert.ok(Number.isFinite(s.mission.targetDistance));assert.equal(s.mission.target.id,s.mission.targets[0].id);assert.equal(s.pilot.active,true);assert.deepEqual(g.mission,original);s.mission.targets[0].visited=true;assert.equal(g.mission.targets[0].visited,false);});
test('the world permits 36 km exploration; its old 5 km boundary is removed',()=>{assert.equal(MAP_EXTENT.width,36000);assert.equal(MAP_EXTENT.depth,36000);assert.deepEqual(Object.keys(MAPS),['coast','valley','island','metro']);const g=makeGame('free');g.state.position.x=12000;g.state.position.z=12000;updateMission(g.mission,g.state,STEP);assert.equal(g.mission.retry,false);g.state.position.x=18001;updateMission(g.mission,g.state,STEP);assert.equal(g.mission.retry,true);});
test('terrain-ahead protection asks the physics for a climb without changing altitude directly',()=>{const g=makeGame('treasure');g.childControl();const before=structuredClone(g.state);const c=updateChildPilot(g.guidance.pilot,g.state,AIRCRAFT.trainer,g.mission,STEP,{terrainAhead:380});assert.deepEqual(g.state,before);assert.equal(g.guidance.pilot.terrainClearance,true);assert.equal(g.guidance.pilot.targetAltitude,520);assert.ok(c.pitch>0);stepPhysics(g.state,c,AIRCRAFT.trainer,STEP);assert.ok(Math.abs(g.state.position.y-before.position.y)<1);});
test('invalid tap values and repeated action taps do not poison or restart guidance',()=>{const g=makeGame('navigation');g.childControl();const p=structuredClone(g.guidance.pilot);for(const d of [NaN,Infinity,undefined,0])g.childTurn(d);g.childControl();assert.deepEqual(g.guidance.pilot,p);const c=updateChildPilot(g.guidance.pilot,g.state,AIRCRAFT.trainer,g.mission,NaN);assert.ok(Object.values(c).every(Number.isFinite));});
test('new child guidance is deterministic for identical physical inputs',()=>{const a=makeGame('mail'),b=makeGame('mail');a.childControl();b.childControl();fly(a,80);fly(b,80);assert.deepEqual(a.state,b.state);assert.deepEqual(a.mission,b.mission);});
test('feedback event ids remain increasing after the retained queue reaches eight entries',()=>{const g=makeGame('treasure');g.mission.events=Array.from({length:8},(_,i)=>({id:i+1,type:'star'}));g.mission.eventSequence=8;for(let i=0;i<2;i++){const target=g.mission.targets[g.mission.passed];Object.assign(g.state.position,{x:target.x,y:target.y,z:target.z});updateMission(g.mission,g.state,STEP);}assert.equal(g.mission.events.length,8);assert.deepEqual(g.mission.events.slice(-2).map(e=>e.id),[9,10]);assert.equal(g.mission.eventSequence,10);});
