import { readSettings } from '../../shared/settings.js';
import { FlightWorld } from './world.js';
import { FlightAudio } from './audio.js';
import { createState,stepPhysics,snapshot,clamp,wrap } from './physics.js';
import { newMission,updateMission,WAYPOINTS } from './mission.js';
import { AIRCRAFT } from './config.js';
export class FlightGame {
  constructor(canvas,onFrame){this.world=new FlightWorld(canvas);this.audio=new FlightAudio();this.controls={pitch:0,roll:0,rudder:0,throttle:0,flaps:0,brake:0};this.keys=new Set();this.mode='menu';this.lesson='takeoff';this.plane='trainer';this.map='coast';this.assist=readSettings().childMode;this.preschool=readSettings().childMode;this.audio.muted=readSettings().muted;this.guidance={rotate:false,navigate:false,land:false};this.state=createState();this.mission=newMission(this.lesson);this.onFrame=onFrame;this.last=performance.now();this.accumulator=0;this.bind();requestAnimationFrame(t=>this.frame(t));}
  bind(){addEventListener('resize',()=>this.world.resize());addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&this.mode!=='menu')e.preventDefault();if(e.target.matches('input,select'))return;this.keys.add(e.code);if(e.repeat)return;if(e.code==='KeyF'&&this.mode==='playing')this.controls.flaps=(this.controls.flaps+1)%3;if(e.code==='KeyC')this.setView(this.world.view==='chase'?'cockpit':'chase');if(e.code==='Escape'&&this.mode!=='menu')this.mode==='paused'?this.resume():this.pause();if(e.code==='KeyR'&&this.mode!=='menu')this.reset();});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>{this.keys.clear();this.controls.pitch=0;this.controls.roll=0;this.controls.rudder=0;if(this.mode==='playing')this.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.mode==='playing')this.pause();});}
  start(lesson=this.lesson,options={}){if(typeof lesson==='object'){options=lesson;lesson=options.lesson||'takeoff';}this.lesson=lesson;this.plane=options.plane||this.plane;this.assist=options.assist??this.assist;this.preschool=options.preschool??this.preschool;this.map=options.map||this.map;this.guidance={rotate:false,navigate:false,land:false};this.world.setMap(this.map);this.state=createState(lesson);if(this.preschool&&(lesson==='takeoff'||lesson==='free'))this.state.flaps=1;this.mission=newMission(lesson);Object.assign(this.controls,{pitch:0,roll:0,rudder:0,throttle:this.state.throttle,flaps:this.state.flaps,brake:0});this.keys.clear();this.mode='playing';this.accumulator=0;this.world.setView(this.world.view);this.audio.start();return this.getState();}
  reset(){return this.start(this.lesson);}
  pause(){if(this.mode==='playing')this.mode='paused';this.audio.update(this.state,false);return this.getState();}
  resume(){if(this.mode==='paused')this.mode='playing';this.keys.clear();this.audio.start();return this.getState();}
  menu(){this.mode='menu';this.keys.clear();this.state=createState();this.controls.throttle=0;this.audio.update(this.state,false);}
  setView(v){this.world.setView(v);}
  getState(){return {mode:this.mode,lesson:this.lesson,plane:this.plane,map:this.map,assist:this.assist,preschool:this.preschool,guidance:{...this.guidance},modelLoaded:this.world.loaded,view:this.world.view,controls:{...this.controls},mission:structuredClone(this.mission),...snapshot(this.state)};}
  childControl(){const s=this.state,p=AIRCRAFT[this.plane];if(this.lesson==='landing'){if(s.grounded){this.controls.throttle=0;return;}this.guidance.land=true;this.controls.flaps=2;}else if(this.lesson==='navigation'){this.guidance.navigate=true;}else if(s.grounded&&s.airspeed<p.rotateSpeed){this.controls.throttle=1;this.controls.flaps=1;}else this.guidance.rotate=true;}
  input(dt){const k=this.keys,s=this.state;let pitch=this.controls.pitch,roll=this.controls.roll,rudder=this.controls.rudder;const value=(pos,neg)=>(k.has(pos)?1:0)-(k.has(neg)?1:0);if(k.has('ArrowUp')||k.has('ArrowDown')||k.has('KeyW')||k.has('KeyS'))pitch=value('ArrowDown','ArrowUp')+value('KeyS','KeyW');if(k.has('ArrowLeft')||k.has('ArrowRight')||k.has('KeyA')||k.has('KeyD'))roll=value('ArrowRight','ArrowLeft')+value('KeyD','KeyA');if(k.has('KeyQ')||k.has('KeyE'))rudder=value('KeyE','KeyQ');if(k.has('ShiftLeft')||k.has('ShiftRight'))this.controls.throttle=Math.min(1,this.controls.throttle+dt*.35);if(k.has('ControlLeft')||k.has('ControlRight'))this.controls.throttle=Math.max(0,this.controls.throttle-dt*.35);
    if(this.preschool){
      if(this.guidance.rotate){pitch=s.position.y<50?clamp((.15-s.pitch)*3-s.pitchRate*.6,-.3,.3):clamp((.13-s.pitch)*2-s.pitchRate*.6,-.2,.2);if(s.position.y>10)this.controls.flaps=0;}
      if(this.guidance.navigate){const w=WAYPOINTS[this.mission.passed]||WAYPOINTS[2],h=Math.atan2(-(w.x-s.position.x),w.z-s.position.z);roll=clamp(wrap(h-s.heading)*.9-s.bank*.8+roll*.25,-.35,.35);pitch=clamp((w.y-s.position.y)*.002-s.velocity.y*.04,-.2,.2);this.controls.throttle=.72;}
      if(this.guidance.land&&!s.grounded){this.controls.throttle=.28;this.controls.flaps=2;pitch=s.position.y<10?.03:0;roll=clamp(-s.bank*.8+s.position.x*.001,-.2,.2);rudder=clamp(-s.heading*.5,-.15,.15);}
      if(s.grounded)rudder+=roll*.7;
    }
    return {...this.controls,pitch,roll,rudder,brake:k.has('Space')?1:this.controls.brake};}
  frame(t){const dt=Math.min(.1,(t-this.last)/1000);this.last=t;if(this.mode==='playing'){this.accumulator+=dt;while(this.accumulator>=1/120){const c=this.input(1/120);this.effectiveControls=c;stepPhysics(this.state,c,AIRCRAFT[this.plane],1/120,{assist:this.assist,onRunway:this.world.onRunway(this.state.position)});updateMission(this.mission,this.state,1/120);this.accumulator-=1/120;if(this.mission.complete||this.mission.retry){this.mode='result';break;}}}this.audio.update(this.state,this.mode==='playing');this.world.render(this.state,this.mission,dt,this.mode==='menu',this.effectiveControls||this.controls);this.onFrame?.(this.getState());requestAnimationFrame(time=>this.frame(time));}
}
