import { KNOTS, FEET } from './physics.js';
export class Instruments {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');}
 draw(s){const c=this.canvas,ctx=this.ctx,w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const radius=Math.min(w/6,h/4)-3,cellw=w/3,cellh=h/2;const items=[['空速','KT',s.airspeed*KNOTS,130],['姿態','',0,0],['高度','FT',s.position.y*FEET,1000],['航向','°',((s.heading*180/Math.PI)%360+360)%360,360],['升降率','FT/M',s.velocity.y*FEET*60,1500],['引擎','RPM',s.rpm,3000]];
 items.forEach((item,i)=>{const x=cellw*(i%3+.5),y=cellh*(Math.floor(i/3)+.5),r=radius;ctx.save();ctx.translate(x,y);ctx.fillStyle='#111c25';ctx.strokeStyle='#476371';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.stroke();
 if(i===1){ctx.save();ctx.beginPath();ctx.arc(0,0,r-2,0,Math.PI*2);ctx.clip();ctx.rotate(-s.bank);const shift=s.pitch*r*1.3;ctx.fillStyle='#4a9ab9';ctx.fillRect(-r*3,-r*3+shift,r*6,r*3);ctx.fillStyle='#9b744e';ctx.fillRect(-r*3,shift,r*6,r*3);ctx.strokeStyle='#f0e5c8';ctx.beginPath();ctx.moveTo(-r*3,shift);ctx.lineTo(r*3,shift);ctx.stroke();for(let p=-2;p<=2;p++){if(!p)continue;ctx.beginPath();ctx.moveTo(-r*.25,shift+p*r*.18);ctx.lineTo(r*.25,shift+p*r*.18);ctx.stroke();}ctx.restore();ctx.strokeStyle='#ffc66c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-r*.7,0);ctx.lineTo(-r*.18,0);ctx.lineTo(0,4);ctx.lineTo(r*.18,0);ctx.lineTo(r*.7,0);ctx.stroke();ctx.fillStyle='#ffffff';ctx.font=`600 ${Math.max(8,r*.19)}px sans-serif`;ctx.textAlign='center';ctx.fillText('姿態',0,-r*.63);ctx.restore();return;}
 for(let k=0;k<13;k++){const a=(-.75+k/12*1.5)*Math.PI;ctx.strokeStyle=i===0&&k>4&&k<10?'#95bf9d':'#8296a0';ctx.beginPath();ctx.moveTo(Math.sin(a)*r*.75,-Math.cos(a)*r*.75);ctx.lineTo(Math.sin(a)*r*.86,-Math.cos(a)*r*.86);ctx.stroke();}
 let value=item[2],max=item[3],a=(-.75+Math.min(1,Math.max(0,i===4?(value+max)/(2*max):value/max))*1.5)*Math.PI;if(i===2)a=(-.75+(value%1000)/1000*1.5)*Math.PI;
 ctx.strokeStyle='#f3d29c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.sin(a)*r*.64,-Math.cos(a)*r*.64);ctx.stroke();ctx.fillStyle='#f3d29c';ctx.beginPath();ctx.arc(0,0,2,0,Math.PI*2);ctx.fill();ctx.textAlign='center';ctx.fillStyle='#d4e1e5';ctx.font=`500 ${Math.max(8,r*.19)}px sans-serif`;ctx.fillText(item[0],0,-r*.33);ctx.fillStyle='#f6f2df';ctx.font=`600 ${Math.max(10,r*.29)}px "Barlow Condensed",sans-serif`;ctx.fillText(Math.round(value).toString().padStart(i===3?3:1,'0'),0,r*.35);ctx.fillStyle='#90a6b1';ctx.font=`500 ${Math.max(7,r*.14)}px sans-serif`;ctx.fillText(item[1],0,r*.58);ctx.restore();});
 }
}
